### PR TITLE
fee-78-s-update-ds01-fee-chs

### PR DESCRIPTION
**Pull request by tcbaileych**
# ** DO NOT MERGE ** until mid-April 2024 AND plan agreed for co-ordinating this with Java upgrade work

## Description

- Updated the fee value from £8 to £33
- Work for this ticket (FEE-76) was done on FEE-78's feature branch

## Jira Ticket

[FEE-76](https://companieshouse.atlassian.net/browse/FEE-76)
[FEE-78](https://companieshouse.atlassian.net/browse/FEE-78)

## Coding Standards

Code Style Guide: https://github.com/companieshouse/dissolution-web/wiki/Code-Style-Guide

## Checklist

- [ ] 3 Amigos
- [x] Acceptance Criteria met
- [ ] Branch named {feature|hotfix|task}/{S4-*}
- [ ] Commit messages are meaningful
- [x] Manually tested
- [x] All unit tests passing
- [ ] API (Karate) tests passing
- [ ] Pulled latest master into feature branch
- [ ] Code reviewed
- [ ] New Docker environment variables have also been added to the revel1 environment and cidev environment
- [ ] If your pull request depends on any other, please link them in the description

## Screenshots of new or updated views

- Demo videos have been recorded for both tickets, showing the user journey and the fee changes meeting the accepted criteria. 
- Screenshots of the acceptance criteria being met are available to see on the Jira Tickets.

[FEE-76]: https://companieshouse.atlassian.net/browse/FEE-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEE-78]: https://companieshouse.atlassian.net/browse/FEE-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by pparlett — APPROVED** [review]
OK, perhaps fee should have been numeric?

**Review by pparlett — APPROVED** [review]
OK, perhaps fee should have been numeric?

**Review by CHssmith2 — APPROVED** [review]
LGTM

**Review by CHssmith2 — APPROVED** [review]
LGTM

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by CHssmith2 — APPROVED** [review]

**Pull request merged**
